# Configuraci√≥n General del Framework Sentinel

app:
  name: "Sentinel Framework"
  version: "1.0.0"
  env: "development"

capture:
  target_keys: "all"
  exclude_special: false
  buffer_size: 10 # teclas antes de escribir en disco

output:
  default_path: "logs/captured_keys.log"
  remote_exfiltration: false
  encryption: false # solo para uso avanzado en lab

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
